name: ct-vessel-resampling
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - scipy
  - scikit-image
  - simpleitk
  - trimesh
  - rtree
  - pillow
  - pyyaml
  - opencv
  - plyfile
  - pytest
