name: ct-vessel-resampling-totalseg-gpu
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - numpy
  - scipy
  - scikit-image
  - simpleitk
  - trimesh
  - pillow
  - pyyaml
  - opencv
  - plyfile
  - pytest
  - pip
  - pip:
      - cupy-cuda13x==14.1.1
      - torch>=2.7
      - TotalSegmentator>=2.11,<3
